@echo off
copy ..\..\src\CExtensibleMarkupLanguageAttribute.cpp Source  1>NUL
copy ..\..\src\CExtensibleMarkupLanguageDocument.cpp  Source  1>NUL
copy ..\..\src\CExtensibleMarkupLanguageElement.cpp   Source  1>NUL
copy ..\..\src\CExtensibleMarkupLanguageEntities.cpp  Source  1>NUL
copy ..\..\src\xml_character_test_routines.cpp        Source  1>NUL
copy ..\..\include\CExtensibleMarkupLanguage.hpp      Include 1>NUL
